baseurl = "https://gtspencer.github.io"
title = "spencerobsitnik"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "spencerobsitnik"

[markup.highlight]
style = "github-dark"

[params]
  author = "Spencer Obsitnik"
  info = "a place for my projects and musings"
  description = "Spencer's website"
  keywords = "blog,developer,personal"
  avatarurl = "images/me.PNG"
  #gravatar = "spencerobsitnik@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"


[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/gtspencer/"

[[params.social]]
  name = "Bluesky"
  icon = "fa-brands fa-bluesky fa-2x"
  weight = 2
  url = "https://bsky.app/profile/0xspencer.bsky.social"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/spencer-obsitnik/"

[[params.social]]
  name = "Youtube"
  icon = "fa-brands fa-youtube fa-2x"
  weight = 4
  url = "https://www.youtube.com/channel/UCyetyYbdXVvQkhB-rfS5ExQ"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"

[[menu.main]]
  name = "Wall (Coming to Steam)"
  weight = 3
  url = "projects/wall"

[[menu.main]]
  name = "SOxSO"
  weight = 5
  url = "shoutouts/"